In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
#graph_object
#express
import plotly.graph_objects as go
import plotly.express as px

In [6]:

#using graph object
#add_trace>>adidng data
#scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(
    
x = [1, 2, 3, 4, 5],   
y = [1, 7, 8, 2, 6],

mode = 'markers'))

In [7]:
import plotly.express as px

x = [1, 2, 3, 4, 5]
y = [10, 20, 15, 30, 25]

fig = px.line(x=x, y=y)

fig.show()

In [8]:
#line chart
fig = go.Figure()
fig.add_trace(go.Scatter(x = [1, 2, 3, 4, 5], y = [1, 7, 8, 2, 6], mode = 'lines'))

In [9]:
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [10]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = tips.total_bill, y = tips.tip, mode = 'markers'))

In [17]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = tips.total_bill, y = tips.tip, mode = 'lines  '))

In [18]:
fig = go.Figure()
fig.add_trace(go.Bar(x = [1, 2, 3, 4, 5], y = [3, 8, 5, 2, 6]))

In [19]:
fig = go.Figure()
fig.add_trace(go.Histogram(x = tips['total_bill']))

In [20]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = tips.total_bill, y = tips.tip, mode = 'markers', marker_size = 12*tips['size']))

In [21]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x = tips.total_bill, y = tips.tip, mode = 'markers', marker_size = 10*tips['size'], z = tips['size']))

In [22]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x = [1, 2, 3, 4, 5], y = [3, 8, 5, 2, 6], z = [1, 2, 7, 3, 5]))

In [28]:
#using plotly express px
x = [1, 2, 3, 4]
y = [10, 13, 15, 18]
fig = px.scatter(x, y)
fig.show()

In [29]:
fig = px.line(x, y)
fig.show()

In [30]:
x = ['A', 'B', 'C']
y = [10, 5, 6]
fig = px.bar(x = x, y = y)
fig.show()

In [31]:
x = [5, 10, 3, 4, 5, 5, 6, 6, 10, 10, 3, 11, 11, 12, 3, 4,]
fig = px.histogram(x)
fig.show()

In [32]:
x = ['A', 'B', 'C']
y = [5, 10, 3, 25, 12, 33, 100]
fig = px.box(x,y)
fig.show()

In [33]:
#plotting heatmap
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
fig = px.imshow(data)
fig.show()

In [34]:
#bubble chart
x = [1, 2, 3, 4]
y = [5, 8, 12, 3]
fig = px.scatter(x, y, size = [30, 10, 50, 100])
fig.show()

In [35]:
#3d chart
x = [1, 2, 3, 4]
y = [5, 8, 12, 3]
z = [3, 4, 5, 6]
fig = px.scatter_3d(x=x, y=y, z=z)
fig.show()

In [36]:
#contour plot
x = [1, 2, 3, 4, 3, 23, 80]
y = [5, 8, 12, 3, 12, 35, 60]
fig = px.density_contour(x, y)
fig.show()

In [42]:
#using add_trace()

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=[1, 2, 3],
        y=[10, 20, 15],
        mode="lines",
        name="Sales"
    )
)

fig.show()

In [40]:
# using px

import plotly.express as px

fig = px.line(
    x=[1, 2, 3],
    y=[10, 20, 15]
)

fig.show()

In [ ]:
# both are  parlale
import plotly.express as px
import plotly.graph_objects as go

fig = px.line(
    x=[1, 2, 3],
    y=[10, 20, 15]
)

fig.add_trace(
    go.Scatter(
        x=[1, 2, 3],
        y=[12, 18, 25],
        mode="lines",
        name="Trend",
        
        
    )
)
fir= px.scatter(
    x=[11,21,31,41,51],
    y=[10,20,30,40,50]
    
)

fig.show()

In [ ]:
import plotly.express as px

fig = px.line(
    x=["Jan", "Feb", "Mar", "Apr"],
    y=[100, 150, 130, 180]
)

fig.update_layout(
    title="Monthly Sales",
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.update_layout(
    title={
        "text": "Sales Report",
        "x": 0.5
    }
)


fig.update_layout(
    template="plotly_dark"
)


fig.show()

In [59]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df = pd.DataFrame({
    "Date": pd.to_datetime([
        "2026-01-01", "2026-01-02", "2026-01-03", "2026-01-04",
        "2026-01-05", "2026-01-06", "2026-01-07", "2026-01-08",
        "2026-01-09", "2026-01-10"
    ]),
    "Product": [
        "Laptop", "Phone", "Tablet", "Laptop", "Phone",
        "Watch", "Tablet", "Laptop", "Phone", "Watch"
    ],
    "Category": [
        "Electronics", "Electronics", "Electronics", "Electronics",
        "Electronics", "Accessories", "Electronics", "Electronics",
        "Electronics", "Accessories"
    ],
    "Region": [
        "North", "South", "East", "West", "North",
        "South", "East", "West", "North", "South"
    ],
    "Sales": [80000, 50000, 30000, 90000, 60000, 20000, 35000, 85000, 55000, 25000],
    "Profit": [12000, 8000, 5000, 15000, 10000, 4000, 6000, 14000, 9000, 4500],
    "Customers": [20, 35, 15, 25, 40, 18, 22, 30, 38, 20]
})

df

        Date Product     Category Region  Sales  Profit  Customers
0 2026-01-01  Laptop  Electronics  North  80000   12000         20
1 2026-01-02   Phone  Electronics  South  50000    8000         35
2 2026-01-03  Tablet  Electronics   East  30000    5000         15
3 2026-01-04  Laptop  Electronics   West  90000   15000         25
4 2026-01-05   Phone  Electronics  North  60000   10000         40
5 2026-01-06   Watch  Accessories  South  20000    4000         18
6 2026-01-07  Tablet  Electronics   East  35000    6000         22
7 2026-01-08  Laptop  Electronics   West  85000   14000         30
8 2026-01-09   Phone  Electronics  North  55000    9000         38
9 2026-01-10   Watch  Accessories  South  25000    4500         20

In [ ]:
# using px:
fig = px.line( # line chart useing for trand / Time 
    df,
    x="Date",
    y="Sales",
    title="sales trands"
)
fig.show()

In [69]:
df.columns

Index(['Date', 'Product', 'Category', 'Region', 'Sales', 'Profit',
       'Customers'],
      dtype='str')

In [74]:
# bar charts : category comparision 
fig = px.bar(
    df,
    x="Product",
    y="Sales",
)
fig.show()

In [72]:
# horizontal bar charts :
fig = px.bar(
    df,
    x="Sales",
    y="Product",
    orientation="h",
    title="Product-wise Sales"
)

fig.show()

In [ ]:
# scatter plots : show the relationship ,means that , numerical vs numerical 
fig = px.scatter(
    df,
    x="Customers",
    y="Sales",
    title="Customers vs Sales"
    
)

fig.show()

In [76]:
# histogram : data distribution 
fig = px.histogram(
    df,
    x="Sales",
    title="Sales Distribution"
)

fig.show()

In [77]:
# bos plot:      usinng for median + spread +outliers
fig = px.box(
    df,
    x="Category",
    y="Sales",
    title="Sales Distribution by Category"
)

fig.show()

In [80]:
# violin plots: distribution shape 

fig = px.violin(
    df,
    x="Region",
    y="Sales",
    title="Sales Distribution by Region",
)

fig.show()

In [81]:
# pie charts : pie = share , proportion 
region_sales = df.groupby("Region", as_index=False)["Sales"].sum()

fig = px.pie(
    region_sales,
    names="Region",
    values="Sales",
    title="Sales Share by Region"
)

fig.show()

In [ ]:
# area charts :  Area = Trend + magnitude 
fig = px.area(
    df,
    x="Date",
    y="Sales",
    title="Sales Area Chart"
)

fig.show()

In [85]:
# funnel charts :  using for process and stage 
funnel_df = pd.DataFrame({
    "Stage": ["Visitors", "Product View", "Add to Cart", "Purchase"],
    "Count": [1000, 700, 400, 200]
})

fig = px.funnel(
    funnel_df,
    x="Count",
    y="Stage",
    title="Sales Funnel"
)

fig.show()

In [87]:
# heatmap :  using for metrix and correlations 
corr = df[["Sales", "Profit", "Customers"]].corr()

fig = px.imshow(
    corr,
    text_auto=True,
    title="Correlation Heatmap"
)

fig.show()

In [88]:
# 3d scatter : 3 numerical variable 
fig = px.scatter_3d(
    df,
    x="Customers",
    y="Sales",
    z="Profit",
    color="Region",
    title="3D Sales Analysis"
)

fig.show()

In [91]:
# colors: means extra information 

fig = px.scatter(
    df,
    x="Customers",
    y="Sales",
    color="Region",
    size="Profit",
    title="Sales by Region"
)

fig.show()

In [92]:
fig = px.scatter(
    df,
    x="Customers",
    y="Sales",
    color="Region",
    symbol="Category",
    title="Sales Analysis"
)

fig.show()

In [97]:
fig.update_layout(
    width=1100,
    height=600
)

fig.show()

In [98]:
fig.update_layout(
    title={
        "text": "Monthly Sales Report",
        "x": 0.5
    }
)

fig.show()

In [100]:
# Axis Labels :

fig.update_layout(
    xaxis_title="Number of Customers",
    yaxis_title="Sales Amount"
)

fig.show()

In [110]:
# Axis Range 
fig.update_yaxes(
    range=[0, 100000]
)

fig.show()

In [116]:
# Rotaete   X- Lable 
fig.update_xaxes(
    tickangle=15
)

fig.show()

In [122]:
# # common Tamplate :
# plotly
# plotly_white
# plotly_dark
# ggplot2
# seaborn
# simple_white

fig.update_layout(
    template="plotly_dark"
    
)

fig.show()

In [128]:
    # line /marker customize

fig.update_traces(
    mode="lines+markers",
    marker=dict(size=10),
    line=dict(width=2)
)

fig.show()

In [133]:
# Legend Customize :  if you are hide  than use False 

fig.update_layout(
    legend_title="Region",
    showlegend=False
)

fig.show()

In [138]:
# Annotation :  Highlight the important Point :

fig.add_annotation(
    x=df["Date"].iloc[-1],
    y=df["Sales"].iloc[-1],
    text="Highest Recent Sales",
    showarrow=True
)

fig.show()